// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using elections.Data;

#nullable disable

namespace elections.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260920011459_StateMacroregionUpperCaseNormalization")]
    partial class StateMacroregionUpperCaseNormalization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("elections.Models.Entities.Macroregion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ID interno da macrorregião.");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("abbr")
                        .HasComment("Sigla da macrorregião.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .HasComment("Nome da macrorregião.");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uid")
                        .HasComment("ID externo da macrorregião.");

                    b.HasKey("Id");

                    b.HasIndex("Abbr")
                        .IsUnique()
                        .HasDatabaseName("IX_macroregion_abbr");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_macroregion_name");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("IX_macroregion_uid");

                    b.ToTable("macroregion", t =>
                        {
                            t.HasComment("Tabela com as 5 macrorregiões brasileiras + 1 registro do Exterior.");

                            t.HasCheckConstraint("CK_macroregion_abbr", "abbr REGEXP '^[A-Z]{1,2}$'");
                        });
                });

            modelBuilder.Entity("elections.Models.Entities.Municipality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ID interno do município.");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsCapital")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_capital")
                        .HasComment("Determina se o município é a capital do Estado. Válido apenas para cidades brasileiras.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name")
                        .HasComment("Nome do município.");

                    b.Property<long>("StateId")
                        .HasColumnType("bigint")
                        .HasColumnName("state_id")
                        .HasComment("ID interno da UF na qual o município está localizado.");

                    b.Property<long>("TseId")
                        .HasColumnType("bigint")
                        .HasColumnName("tse_id")
                        .HasComment("Código do TSE ligado ao município que pode ser visto nos arquivos de resultados.");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uid")
                        .HasComment("ID externo do município.");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.HasIndex("TseId")
                        .IsUnique()
                        .HasDatabaseName("IX_municipality_tse_id");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("IX_municipality_uid");

                    b.ToTable("municipality", t =>
                        {
                            t.HasComment("Tabela com os municípios brasileiros ou cidades estrangeiras com votações de eleições brasilieiras. Pode aceitar duplicatas de cidades do exterior porque, nesses casos, o TSE dá um código diferente a cada seção eleitoral, ainda que da mesma localidade.");
                        });
                });

            modelBuilder.Entity("elections.Models.Entities.State", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ID interno da UF.");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("abbr")
                        .HasComment("Sigla da UF.");

                    b.Property<long>("MacroregionId")
                        .HasColumnType("bigint")
                        .HasColumnName("macroregion_id")
                        .HasComment("ID interno da macroregião na qual a UF está localizada.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Nome da UF.");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uid")
                        .HasComment("ID externo da UF.");

                    b.HasKey("Id");

                    b.HasIndex("Abbr")
                        .IsUnique()
                        .HasDatabaseName("IX_state_abbr");

                    b.HasIndex("MacroregionId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_state_name");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("IX_state_uid");

                    b.ToTable("state", t =>
                        {
                            t.HasComment("Tabela com 27 UFs do Brasil + 1 registro indicando Exterior.");

                            t.HasCheckConstraint("CK_state_abbr", "abbr REGEXP '^[A-Z]{2}$'");
                        });
                });

            modelBuilder.Entity("elections.Models.Entities.Municipality", b =>
                {
                    b.HasOne("elections.Models.Entities.State", "State")
                        .WithMany("Municipalities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_municipality_state");

                    b.Navigation("State");
                });

            modelBuilder.Entity("elections.Models.Entities.State", b =>
                {
                    b.HasOne("elections.Models.Entities.Macroregion", "Macroregion")
                        .WithMany("States")
                        .HasForeignKey("MacroregionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_state_macroregion");

                    b.Navigation("Macroregion");
                });

            modelBuilder.Entity("elections.Models.Entities.Macroregion", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("elections.Models.Entities.State", b =>
                {
                    b.Navigation("Municipalities");
                });
#pragma warning restore 612, 618
        }
    }
}
