// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using elections.Data;

#nullable disable

namespace elections.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260922221837_ElectionTables")]
    partial class ElectionTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("elections.Models.Entities.Candidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ID interno do candidato.");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Biography")
                        .HasColumnType("longtext")
                        .HasColumnName("biography");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date")
                        .HasComment("Data de nascimento do candidato. Pode ser um dado difícil de encontrar em eleições mais remotas, por isso é anulável.");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date")
                        .HasColumnName("death_date")
                        .HasComment("Data de falecimento do candidato. É nula quando o candidato está vivo ou pelo mesmo motivo de birth_date.");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("display_name")
                        .HasComment("Nome de exibição do candidato — o que é exibido nos resultados eleitorais.");

                    b.Property<bool>("IsDeceased")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deceased")
                        .HasComment("Campo booleano que determina se o candidato é falecido ou não");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Nome completo do candidato.");

                    b.Property<string>("TseName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tse_name")
                        .HasComment("Nome do candidato que aparece nos arquivos de resultados eleitorais do TSE que serve como referência de ingestão dos dados de votação. Às vezes pode ser igual o nome completo, ou um apelido, ou o nome completo sem algum sobrenome específico. Por isso a necessidade de haver esse campo.");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uid")
                        .HasComment("ID externo do candidato.");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique()
                        .HasDatabaseName("IX_candidate_display_name");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_candidate_name");

                    b.HasIndex("TseName")
                        .IsUnique()
                        .HasDatabaseName("IX_candidate_tse_name");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("IX_candidate_uid");

                    b.ToTable("candidate", t =>
                        {
                            t.HasComment("Tabela com os candidatos e os respectivos dados pessoais de cada um.");
                        });
                });

            modelBuilder.Entity("elections.Models.Entities.CandidateParty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ID interno da relação.");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CandidateId")
                        .HasColumnType("bigint")
                        .HasColumnName("candidate_id")
                        .HasComment("ID interno do candidato.");

                    b.Property<long>("PartyId")
                        .HasColumnType("bigint")
                        .HasColumnName("party_id")
                        .HasComment("ID interno do partido.");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.HasIndex("CandidateId", "PartyId")
                        .IsUnique()
                        .HasDatabaseName("IX_candidate_party");

                    b.ToTable("candidate_party", t =>
                        {
                            t.HasComment("Tabela de relação entre um candidato e um partido político — a filiação de um político a determinado partido.");
                        });
                });

            modelBuilder.Entity("elections.Models.Entities.Election", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ID interno da eleição.");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("FK_election_municipality_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("FK_election_state_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("MunicipalityId")
                        .HasColumnType("bigint")
                        .HasColumnName("municipality_id")
                        .HasComment("ID interno do munícipio caso o cargo em disputa for Prefeito, Vereador ou algum outro cargo correlato a nível municipal.");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role")
                        .HasComment("Cargo em disputa da eleição.");

                    b.Property<long?>("StateId")
                        .HasColumnType("bigint")
                        .HasColumnName("state_id")
                        .HasComment("ID interno da UF caso o cargo em disputa for Governador do Estado, Deputado Estadual ou Federal, Senador, ou algum outro cargo com relação direta à UF.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type")
                        .HasComment("O tipo da eleição.");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uid")
                        .HasComment("ID externo da eleição.");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("FK_election_municipality_id");

                    b.HasIndex("FK_election_state_id");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("IX_election_uid");

                    b.ToTable("election", t =>
                        {
                            t.HasComment("Tabela com as eleições.");

                            t.HasCheckConstraint("CK_election_role", "role IN \r\n(\r\n    'PRESIDENTE', \r\n    'GOVERNADOR', \r\n    'PREFEITO', \r\n    'SENADOR',\r\n    'DEPUTADO FEDERAL',\r\n    'DEPUTADO ESTADUAL',\r\n    'VEREADOR'\r\n)");

                            t.HasCheckConstraint("CK_election_role_scope", "(\r\n    role = 'PRESIDENTE' \r\n    AND municipality_id IS NULL\r\n    AND state_id IS NULL\r\n)\r\nOR\r\n(   role IN\r\n    (\r\n        'GOVERNADOR',\r\n        'SENADOR',\r\n        'DEPUTADO FEDERAL',\r\n        'DEPUTADO ESTADUAL'\r\n    )\r\n    AND municipality_id IS NULL \r\n    AND state_id IS NOT NULL\r\n)\r\nOR\r\n(   role IN\r\n    (\r\n        'PREFEITO',\r\n        'VEREADOR'\r\n    )\r\n    AND municipality_id IS NOT NULL \r\n    AND state_id IS NULL\r\n)");

                            t.HasCheckConstraint("CK_election_type", "type IN \r\n(\r\n    'Ordinária', \r\n    'Suplementar'\r\n)");
                        });
                });

            modelBuilder.Entity("elections.Models.Entities.ElectionRound", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ID interno do turno da eleição.");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ElectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("election_id")
                        .HasComment("ID interno da eleição.");

                    b.Property<DateOnly>("HeldAt")
                        .HasColumnType("date")
                        .HasColumnName("held_at")
                        .HasComment("Data da realização do turno da eleição.");

                    b.Property<int>("NrRound")
                        .HasColumnType("int")
                        .HasColumnName("nr_round")
                        .HasComment("Número do turno da eleição.");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uid")
                        .HasComment("ID externo do turno da eleição.");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("IX_election_round_uid");

                    b.HasIndex("ElectionId", "NrRound")
                        .HasDatabaseName("IX_election_round_election_nr_round");

                    b.ToTable("election_round", t =>
                        {
                            t.HasComment("Tabela com os turnos de eleições.");

                            t.HasCheckConstraint("CK_election_round", "nr_round IN (1, 2)");
                        });
                });

            modelBuilder.Entity("elections.Models.Entities.Macroregion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ID interno da macrorregião.");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("abbr")
                        .HasComment("Sigla da macrorregião.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .HasComment("Nome da macrorregião.");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uid")
                        .HasComment("ID externo da macrorregião.");

                    b.HasKey("Id");

                    b.HasIndex("Abbr")
                        .IsUnique()
                        .HasDatabaseName("IX_macroregion_abbr");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_macroregion_name");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("IX_macroregion_uid");

                    b.ToTable("macroregion", t =>
                        {
                            t.HasComment("Tabela com as 5 macrorregiões brasileiras + 1 registro do Exterior.");

                            t.HasCheckConstraint("CK_macroregion_abbr", "abbr REGEXP '^[A-Z]{1,2}$'");
                        });
                });

            modelBuilder.Entity("elections.Models.Entities.MetropolitanArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ID interno da região metropolitana.");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name")
                        .HasComment("Nome da região metropolitana.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type")
                        .HasComment("Tipo da região metropolitana.");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uid")
                        .HasComment("ID externo da região metropolitana.");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_metropolitan_area_name");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("IX_metropolitan_area_uid");

                    b.ToTable("metropolitan_area", t =>
                        {
                            t.HasComment("Tabela com regiões metropolitanas e regiões integradas de desenvolvimento");

                            t.HasCheckConstraint("CK_metropolitan_area_type", "type IN ('REGIÃO METROPOLITANA', 'REGIÃO INTEGRADA DE DESENVOLVIMENTO')");
                        });
                });

            modelBuilder.Entity("elections.Models.Entities.Municipality", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ID interno do município.");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("IbgeId")
                        .HasColumnType("bigint")
                        .HasColumnName("ibge_id")
                        .HasComment("ID do município no IBGE.");

                    b.Property<bool>("IsCapital")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_capital")
                        .HasComment("Determina se o município é a capital do Estado. Válido apenas para cidades brasileiras.");

                    b.Property<long?>("MetropolitanAreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("metropolitan_area_id")
                        .HasComment("ID interno da região metropolitana na qual o município pode estar localizado.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name")
                        .HasComment("Nome do município.");

                    b.Property<long>("StateId")
                        .HasColumnType("bigint")
                        .HasColumnName("state_id")
                        .HasComment("ID interno da UF na qual o município está localizado.");

                    b.Property<long>("TseId")
                        .HasColumnType("bigint")
                        .HasColumnName("tse_id")
                        .HasComment("Código do TSE ligado ao município que pode ser visto nos arquivos de resultados.");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uid")
                        .HasComment("ID externo do município.");

                    b.HasKey("Id");

                    b.HasIndex("IbgeId")
                        .IsUnique()
                        .HasDatabaseName("IX_municipality_ibge_id");

                    b.HasIndex("MetropolitanAreaId");

                    b.HasIndex("StateId");

                    b.HasIndex("TseId")
                        .IsUnique()
                        .HasDatabaseName("IX_municipality_tse_id");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("IX_municipality_uid");

                    b.ToTable("municipality", t =>
                        {
                            t.HasComment("Tabela com os municípios brasileiros ou cidades estrangeiras com votações de eleições brasilieiras. Pode aceitar duplicatas de cidades do exterior porque, nesses casos, o TSE dá um código diferente a cada seção eleitoral, ainda que da mesma localidade.");
                        });
                });

            modelBuilder.Entity("elections.Models.Entities.Party", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ID interno do partido.");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("abbr")
                        .HasComment("Sigla do partido.");

                    b.Property<DateOnly?>("DissolvedAt")
                        .HasColumnType("date")
                        .HasColumnName("dissolved_at")
                        .HasComment("Data de dissolução/mudança de nome/fusão/incorporação do partido.");

                    b.Property<DateOnly?>("FoundedAt")
                        .HasColumnType("date")
                        .HasColumnName("founded_at")
                        .HasComment("Data de fundação do partido.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasComment("Campo booleano que determina se o partido está ativo ou não.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name")
                        .HasComment("Nome completo do partido.");

                    b.Property<short>("NrVoteable")
                        .HasColumnType("smallint")
                        .HasColumnName("nr_voteable")
                        .HasComment("Número do partido.");

                    b.Property<DateOnly>("RegisteredAt")
                        .HasColumnType("date")
                        .HasColumnName("registered_at")
                        .HasComment("Data de registro do partido junto ao TSE.");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uid")
                        .HasComment("ID externo do partido.");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("IX_party_uid");

                    b.ToTable("party", t =>
                        {
                            t.HasComment("Tabela com os partidos políticos. Pode ter registros do mesmo partido se ele mudou de nome ou se fundiu-se ou incorporou-se a outro partido.");
                        });
                });

            modelBuilder.Entity("elections.Models.Entities.State", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ID interno da UF.");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("abbr")
                        .HasComment("Sigla da UF.");

                    b.Property<long>("MacroregionId")
                        .HasColumnType("bigint")
                        .HasColumnName("macroregion_id")
                        .HasComment("ID interno da macroregião na qual a UF está localizada.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("Nome da UF.");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("uid")
                        .HasComment("ID externo da UF.");

                    b.HasKey("Id");

                    b.HasIndex("Abbr")
                        .IsUnique()
                        .HasDatabaseName("IX_state_abbr");

                    b.HasIndex("MacroregionId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_state_name");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasDatabaseName("IX_state_uid");

                    b.ToTable("state", t =>
                        {
                            t.HasComment("Tabela com 27 UFs do Brasil + 1 registro indicando Exterior.");

                            t.HasCheckConstraint("CK_state_abbr", "abbr REGEXP '^[A-Z]{2}$'");
                        });
                });

            modelBuilder.Entity("elections.Models.Entities.CandidateParty", b =>
                {
                    b.HasOne("elections.Models.Entities.Candidate", "Candidate")
                        .WithMany("CandidateParties")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_candidate_party_candidate");

                    b.HasOne("elections.Models.Entities.Party", "Party")
                        .WithMany("CandidateParties")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_candidate_party_party");

                    b.Navigation("Candidate");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("elections.Models.Entities.Election", b =>
                {
                    b.HasOne("elections.Models.Entities.Municipality", "Municipality")
                        .WithMany("Elections")
                        .HasForeignKey("FK_election_municipality_id");

                    b.HasOne("elections.Models.Entities.State", "State")
                        .WithMany("Elections")
                        .HasForeignKey("FK_election_state_id");

                    b.Navigation("Municipality");

                    b.Navigation("State");
                });

            modelBuilder.Entity("elections.Models.Entities.ElectionRound", b =>
                {
                    b.HasOne("elections.Models.Entities.Election", "Election")
                        .WithMany("ElectionRounds")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_election_round_election_id");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("elections.Models.Entities.Municipality", b =>
                {
                    b.HasOne("elections.Models.Entities.MetropolitanArea", "MetropolitanArea")
                        .WithMany("Municipalities")
                        .HasForeignKey("MetropolitanAreaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_municipality_metropolitan_area");

                    b.HasOne("elections.Models.Entities.State", "State")
                        .WithMany("Municipalities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_municipality_state");

                    b.Navigation("MetropolitanArea");

                    b.Navigation("State");
                });

            modelBuilder.Entity("elections.Models.Entities.State", b =>
                {
                    b.HasOne("elections.Models.Entities.Macroregion", "Macroregion")
                        .WithMany("States")
                        .HasForeignKey("MacroregionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_state_macroregion");

                    b.Navigation("Macroregion");
                });

            modelBuilder.Entity("elections.Models.Entities.Candidate", b =>
                {
                    b.Navigation("CandidateParties");
                });

            modelBuilder.Entity("elections.Models.Entities.Election", b =>
                {
                    b.Navigation("ElectionRounds");
                });

            modelBuilder.Entity("elections.Models.Entities.Macroregion", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("elections.Models.Entities.MetropolitanArea", b =>
                {
                    b.Navigation("Municipalities");
                });

            modelBuilder.Entity("elections.Models.Entities.Municipality", b =>
                {
                    b.Navigation("Elections");
                });

            modelBuilder.Entity("elections.Models.Entities.Party", b =>
                {
                    b.Navigation("CandidateParties");
                });

            modelBuilder.Entity("elections.Models.Entities.State", b =>
                {
                    b.Navigation("Elections");

                    b.Navigation("Municipalities");
                });
#pragma warning restore 612, 618
        }
    }
}
