DF_TSE_ID_COLUMN = "cd_municipio"
DF_MUNICIPALTY_NAME_COLUMN = "nm_municipio"
DF_MUNICIPALTY_ID_COLUMN = "id_municipio"
DF_METROPOLITAN_AREA_NAME_COLUMN = "nm_metro"
DF_METROPOLITAN_AREA_ID_COLUMN = "id_metro"
DF_STATE_ABBR_COLUMN = "sg_uf"
DF_STATE_ID_COLUMN = "id_uf"
DF_MACROREGION_ID_COLUMN = "id_macrorregiao"
DF_IBGE_ID_COLUMN = "cd_ibge"
DF_IS_CAPITAL_COLUMN = "capital"
DF_CANDIDATE_NAME_COLUMN = "nm_votavel"
DF_QT_VOTES_COLUMN = "qt_votos"
DF_QT_VALID_VOTES_COLUMN = "qt_votos_validos"
DF_PP_VALID_VOTES_COLUMN = "pp_votos_validos"
DF_PP_VALID_VOTES_REGISTERED_COLUMN = "pp_votos_validos_inscritos"
DF_NULL_VOTES_NAME = "VOTO NULO"
DF_QT_NULL_VOTES_COLUMN = "qt_votos_nulos"
DF_PP_NULL_VOTES_COLUMN = "pp_votos_nulos_votos"
DF_PP_NULL_VOTES_REGISTERED_COLUMN = "pp_votos_nulos_inscritos"
DF_BLANK_VOTES_NAME = "VOTO BRANCO"
DF_QT_BLANK_VOTES_COLUMN = "qt_votos_brancos"
DF_PP_BLANK_VOTES_COLUMN = "pp_votos_brancos"
DF_PP_BLANK_VOTES_REGISTERED_COLUMN = "pp_votos_brancos_inscritos"
DF_ANULLED_VOTES_NAME = "VOTO ANULADO E APURADO EM SEPARADO"
DF_QT_ANULLED_VOTES_COLUMN = "qt_votos_anulados"
DF_PP_ANULLED_VOTES_COLUMN = "pp_votos_anulados"
DF_PP_ANULLED_VOTES_REGISTERED_COLUMN = "pp_votos_anulados_inscritos"
DF_INVALID_VOTES = [DF_NULL_VOTES_NAME, DF_BLANK_VOTES_NAME, DF_ANULLED_VOTES_NAME]
DF_INVALID_VOTES_COLUMN = "qt_votos_invalidos"
DF_PP_INVALID_VOTES_COLUMN = "pp_votos_invalidos"
DF_PP_INVALID_VOTES_REGISTERED_COLUMN = "pp_votos_invalidos_inscritos"
DF_CANDIDATE_BIRTH_DATE_COLUMN = "dt_aniversario"
DF_TICKET_ID_COLUMN = "cd_chapa"
DF_NR_POSITION_COLUMN = "nr_posicao"
DF_TICKET_STATUS_COLUMN = "situacao_chapa"
DF_QT_REGISTERED_VOTERS_COLUMN = "qt_aptos"
DF_QT_TURNOUT_COLUMN = "qt_comparecimento"
DF_PP_TURNOUT_COLUMN = "pp_comparecimento"
DF_QT_ABSTENTION_COLUMN = "qt_abstencao"
DF_PP_ABSTENTION_COLUMN = "pp_abstencao"
DF_QT_ELECTORAL_ALIENATION_COLUMN = "qt_alienacao_eleitoral"
DF_PP_ELECTORAL_ALIENATION_COLUMN = "pp_alienacao_eleitoral"
DF_PP_TICKET_VALID_VOTES_COLUMN = "pp_votos_validos_chapa"
DF_PP_TICKET_TOTAL_VOTES_COLUMN = "pp_votos_totais_chapa"
DF_PP_TICKET_REGISTERED_VOTES_COLUMN = "pp_votos_validos_inscritos_chapa"
DF_ELECTION_ROUND_ID_COLUMN = "id_eleicao"
DF_QT_CANDIDATES_COLUMN = "qt_candidatos"


GDF_IBGE_ID_COLUMN = "CD_MUN"
GDF_MUNICIPALTY_NAME_COLUMN = "NM_MUN"
GDF_METROPOLITAN_AREA_NAME_COLUMN = "NM_METRO"
GDF_STATE_ABBR_COLUMN = "SG_UF"


CAPITAL_IBGE_IDS = [
    5300108,
    5208707,
    5103403,
    5002704,
    3550308,
    3304557,
    3106200,
    3205309,
    4314902,
    4205407,
    4106902,
    2704302,
    2800308,
    2927408,
    2408102,
    2507507,
    2611606,
    2111300,
    2211001,
    2304400,
    1302603,
    1501402,
    1600303,
    1100205,
    1200401,
    1400100,
    1721000
]

ELECTED = "ELEITO"
NOT_ELECTED = "NÃO ELEITO"
RUNOFF = "2º TURNO"

PRESIDENT = "PRESIDENTE"
GOVERNOR = "GOVERNADOR"
MAYOR = "PREFEITO"
SENATOR = "SENATOR"
HOUSE_REPRESENTATIVE = "DEPUTADO FEDERAL"
STATE_REPRESENTATIVE = "DEPUTADO ESTADUAL"
CITY_COUNCILOR = "VEREADOR"
ROLES = [PRESIDENT, GOVERNOR, MAYOR, SENATOR, HOUSE_REPRESENTATIVE, STATE_REPRESENTATIVE, CITY_COUNCILOR]